### ISSUE TITLE
v0.3.1-alpha: step 5 bubblegun is infrastructure specific

### ISSUE THREAD

**Issue by ptrebert** [marschall-lab/strand-seq-graph-phasing#42]
The path to the pip config file is (obviously) not the same on all infrastructures. The readme lacks a better explanation for what is happening there and should make use of the offline deploy switch to select an appropriate conda env file for the bubblegun rule.

A possible way to properly hide this setup mess would be to provide a singularity def file just for BubbleGun and to deploy that as a container.

**Comment by mir-cat** [comment]
So the bubblegun package isn't actually needed anymore, and is at this point vestigial. I have been working on updating the readme and files included in the repo to reflect that.

**Comment by ptrebert** [comment]
vestigial ... I had to google that ...
Ok, then just for the record in case it's still needed for older versions / reproducibility, the bubble gun setup does not work with Python 3.12, i.e. the conda env would need to include `python=3.11` to make it work.

This is the error:
```
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```
Here is the explanation:
https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean
